### ISSUE TITLE
BLAS++ & LAPACK++ moved to GitHub: need to update continuous integration scripts.

### ISSUE THREAD

**Issue by TeachRaccooon** [BallisticLA/RandLAPACK#17]
The new URLs are:
https://github.com/icl-utk-edu/blaspp.git
https://github.com/icl-utk-edu/lapackpp.git
Tried to apply the change, build failed per compilation error:
https://github.com/BallisticLA/RandLAPACK/actions/runs/3951487969/jobs/6765402759

**Comment by rileyjmurray** [comment]
Per Burlen's comment [here](https://github.com/BallisticLA/RandLAPACK/pull/16#issuecomment-1398816766), the problem stemmed from not rebasing changes from main onto the feature branch. The rebasing is needed because it includes information about version of the RandBLAS that RandLAPACK needs to be built against. I believe that @burlen changed the RandLAPACK continuous integration settings so that the necessary rebasing will happen automatically (please correct me if I'm wrong on that).

If similar error messages arise in the future, then the first troubleshooting step should be to make sure you've rebased main onto a feature branch. It won't suffice to just manually copy-paste the contents of source code / CMake files so that a feature branch matches main!

**Comment by rileyjmurray** [comment]
This will be resolved by PR #38.

**Comment by rileyjmurray** [comment]
Resolved.
